<?php

declare (strict_types=1);
namespace home\enterprise\cadastroServiceCar;

use home\enterprise\Model;
use home\errors\InvalidArgument;

class ServicosCar extends Model
{
    protected $name;
    protected $email;
    protected $fone;
    protected $posX;
    protected $posY;
    protected $endereco;

    function __construct(string $name , string $email , string $fone)
    {
        if($name== null || $email==null || $fone==null){
            throw new InvalidArgument("Todos os campos devem ser preenchidos.");
        }

        if ( preg_match("/[^a-zA-Z]/'[ ]'/",$name) == 1){
            throw new InvalidArgument("$name, No Nome deve conter apenas letras");
        }


        $this->name = $name;
        $this->email = $email;
        $this->fone = $fone;
    }

    /**
     * @param mixed $localizacao
     */
    public function setLocalizacao(double $posX , double $posY):array
    {
        $localizacao = [$posX , $posY];
        return $localizacao;
    }

    public function setEndereço(string $endereco)
    {
        $this->endereco = $endereco;
    }

    /**
     * @return string
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * @return string
     */
    public function getFone(): string
    {
        return $this->fone;
    }

    /**
     * @return string
     */
    public function getEmail(): string
    {
        return $this->email;
    }

    /**
     * @return mixed
     */
    public function getLocalizacao()
    {
        return $this->localizacao;
    }

    /**
     * @return mixed
     */
    public function getEndereco()
    {
        return $this->endereco;
    }

    public function getClassName()
    {
        return 'ServicosCar';
    }

    public function getIdAttribute()
    {
        return 'fone'; // TODO: Change the autogenerated stub
    }


}